export interface FoodDataItem {
   name: string;
   path: string;
   favorite: boolean;
}

export const FOOD_ITEMS: FoodDataItem[] = [
   { name: "Iced americano and lemongrass lemonade in Paris", path: "/food/food-01.jpg", favorite: false },
   { name: "Tonkotsu ramen with soft-boiled eggs", path: "/food/food-02.jpg", favorite: false },
   { name: "Chocolate-drizzled pastry squares", path: "/food/food-03.jpg", favorite: false },
   { name: "Espresso at sunset over the sea", path: "/food/food-04.jpg", favorite: true },
   { name: "Thai basil fried rice with fried egg", path: "/food/food-05.jpg", favorite: false },
   { name: "Full breakfast with eggs, bacon and toast", path: "/food/food-06.jpg", favorite: false },
   { name: "Margherita pizza and creamy mushroom pappardelle", path: "/food/food-07.jpg", favorite: true },
   { name: "Cheese omelette with toast and sausages", path: "/food/food-08.jpg", favorite: false },
   { name: "Thai boat noodle soup with spring rolls", path: "/food/food-09.jpg", favorite: false },
   { name: "Hot pot with sliced beef, pork and seafood", path: "/food/food-10.jpg", favorite: false },
   { name: "Crispy chicken and fried egg over rice", path: "/food/food-11.jpg", favorite: true },
   { name: "Char siu pork rice bowl with fried egg", path: "/food/food-12.jpg", favorite: false },
   { name: "Sweet soy fried chicken bites over rice", path: "/food/food-13.jpg", favorite: true },
   { name: "Portuguese egg tart", path: "/food/food-14.jpg", favorite: false },
   { name: "Whole roasted chicken platter", path: "/food/food-15.jpg", favorite: false },
   { name: "Thai green curry with rice", path: "/food/food-16.jpg", favorite: true },
   { name: "Braised beef soup with rice noodles", path: "/food/food-17.jpg", favorite: false },
   { name: "Beef and vegetable udon soup", path: "/food/food-18.jpg", favorite: false },
   { name: "Salmon sashimi chirashi bowl", path: "/food/food-19.jpg", favorite: false },
   { name: "Butter chicken curry with rice", path: "/food/food-20.jpg", favorite: false },
   { name: "Korean BBQ grilled pork belly", path: "/food/food-21.jpg", favorite: false },
   { name: "Cambodian rice plate with grilled pork and egg", path: "/food/food-22.jpg", favorite: false },
   { name: "Breaded fish schnitzel with spaghetti pomodoro", path: "/food/food-23.jpg", favorite: true },
   { name: "Fried chicken and pancake brunch at Miffy Café", path: "/food/food-24.jpg", favorite: false },
   { name: "Iced tea at Wat Chaiwatthanaram, Ayutthaya", path: "/food/food-25.jpg", favorite: false },
   { name: "Iced matcha with soufflé pancakes and breakfast", path: "/food/food-26.jpg", favorite: false },
   { name: "Braised pork claypot with garlic and herbs", path: "/food/food-27.jpg", favorite: false },
   { name: "Chocolate chip cookie", path: "/food/food-28.jpg", favorite: true },
   { name: "Starbucks coffee and chocolate chip muffin", path: "/food/food-29.jpg", favorite: false },
   { name: "Star-folded galette complète with egg and chicken", path: "/food/food-30.jpg", favorite: false },
   { name: "Nutella crêpe with chocolate sauce", path: "/food/food-31.jpg", favorite: false },
   { name: "Fried gyoza dumplings with Thai iced tea", path: "/food/food-32.jpg", favorite: false },
   { name: "Banana cake slices", path: "/food/food-33.jpg", favorite: true },
   { name: "Tiramisu slice", path: "/food/food-34.jpg", favorite: true },
   { name: "Big breakfast spread with french toast and pancakes", path: "/food/food-35.jpg", favorite: false },
   { name: "Margherita pizza and creamy carbonara-style pasta", path: "/food/food-36.jpg", favorite: false },
   { name: "Molten chocolate chip cookie", path: "/food/food-37.jpg", favorite: false },
   { name: "Tiramisu with coffee ice cream dessert", path: "/food/food-38.jpg", favorite: true },
   { name: "Chicken fried rice", path: "/food/food-39.jpg", favorite: false },
   { name: "Bun cha with grilled pork and rice vermicelli", path: "/food/food-40.jpg", favorite: true },
   { name: "Homemade sticky rice with mango", path: "/food/food-41.jpg", favorite: false },
   { name: "Homemade crêpe cooking in a pan", path: "/food/food-42.jpg", favorite: false },
   { name: "Thai green curry with rice", path: "/food/food-43.jpg", favorite: false },
   { name: "Brownie with iced tea and a lime cocktail", path: "/food/food-44.jpg", favorite: false },
   { name: "Thick pancake with tea and syrup", path: "/food/food-45.jpg", favorite: false },
   { name: "Iced lemon ginger drink to go", path: "/food/food-46.jpg", favorite: true },
   { name: "Thai fried rice with fried egg and clear soup", path: "/food/food-47.jpg", favorite: false },
   { name: "Instant noodle soup with pork, egg and greens", path: "/food/food-48.jpg", favorite: false },
   { name: "Thai fried rice, curry and iced lime drink", path: "/food/food-49.jpg", favorite: false },
   { name: "Pan-fried gyoza with tonkotsu ramen", path: "/food/food-50.jpg", favorite: false },
   { name: "Filipino sisig with pork skewers and rice", path: "/food/food-51.jpg", favorite: false },
   { name: "Thai basil pork stir-fry with green curry and rice", path: "/food/food-52.jpg", favorite: true },
   { name: "Tiramisu and cheesecake desserts at Esalta", path: "/food/food-53.jpg", favorite: true },
   { name: "Lasagna with a glass of beer", path: "/food/food-54.jpg", favorite: false },
   { name: "Gnocchi in tomato sauce with an Aperol spritz", path: "/food/food-55.jpg", favorite: false },
   { name: "Gelato cup with a wafer cone", path: "/food/food-56.jpg", favorite: false },
   { name: "Schnitzel with mushroom sauce and fries", path: "/food/food-57.jpg", favorite: false },
   { name: "Stack of crêpes with Nutella", path: "/food/food-58.jpg", favorite: true },
   { name: "Iced matcha latte on a Paris street", path: "/food/food-59.jpg", favorite: false },
   { name: "Grilled ribeye steak with mushrooms and salad", path: "/food/food-60.jpg", favorite: false },
];
